# Generated by Django 5.2.17 on 2026-08-13 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Naslov')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Kratak opis')),
                ('body', models.TextField(help_text='Možete formatirati tekst i ubaciti slike.', verbose_name='Tekst')),
                ('cover', models.ImageField(blank=True, upload_to='aktuelnosti/covers/', verbose_name='Naslovna slika')),
                ('is_published', models.BooleanField(default=False, verbose_name='Objavljeno')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Datum objave')),
                ('language', models.CharField(choices=[('sr', 'Srpski'), ('en', 'English'), ('ru', 'Русский')], default='sr', max_length=5, verbose_name='Jezik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aktuelnost',
                'verbose_name_plural': 'Aktuelnosti',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Ime i prezime')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Poruka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Pročitano')),
            ],
            options={
                'verbose_name': 'Poruka sa sajta',
                'verbose_name_plural': 'Poruke sa sajta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aktuelnosti/gallery/', verbose_name='Slika')),
                ('caption', models.CharField(blank=True, max_length=220, verbose_name='Opis slike')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Redosled')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.article', verbose_name='Članak')),
            ],
            options={
                'verbose_name': 'Slika članka',
                'verbose_name_plural': 'Slike članka',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
