# Generated by Django 5.2.17 on 2026-08-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Prikazuje se u gornjem headeru kada se otvori aktuelnost.', upload_to='aktuelnosti/headers/', verbose_name='Slika za header'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, help_text='Prikazuje se na početnoj i na listi aktuelnosti.', upload_to='aktuelnosti/covers/', verbose_name='Glavna slika'),
        ),
    ]
