# Generated by Django 5.2.17 on 2026-08-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_article_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(help_text='Glavni sadržaj vesti. Možete formatirati tekst i ubaciti slike.', verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, help_text='Prikazuje se na listi, na početnoj i u headeru vesti ako nema posebne header slike.', upload_to='aktuelnosti/covers/', verbose_name='Slika'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Prikazuje se na listi aktuelnosti i na početnoj.', verbose_name='Kratak opis'),
        ),
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Opciono. Ako je prazno, koristi se slika iznad.', upload_to='aktuelnosti/headers/', verbose_name='Slika za header'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Objavljeno'),
        ),
    ]
