# Generated by Django 5.2.17 on 2026-08-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_article_publish_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Naziv saradnika')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Iznos')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('status', models.CharField(choices=[('active', 'Aktivan'), ('pending', 'Na čekanju'), ('completed', 'Završen'), ('paused', 'Pauziran')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saradnik',
                'verbose_name_plural': 'Saradnici',
                'ordering': ['name'],
            },
        ),
    ]
