# Generated by Django 5.2.17 on 2026-08-18 14:12

import django.utils.timezone
from django.db import migrations, models


def fill_recorded_on(apps, schema_editor):
    Partner = apps.get_model('website', 'Partner')
    for partner in Partner.objects.all():
        if partner.created_at:
            partner.recorded_on = partner.created_at.date()
            partner.save(update_fields=['recorded_on'])


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-recorded_on', 'name'], 'verbose_name': 'Saradnja', 'verbose_name_plural': 'Saradnja'},
        ),
        migrations.AddField(
            model_name='partner',
            name='recorded_on',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Datum'),
        ),
        migrations.RunPython(fill_recorded_on, migrations.RunPython.noop),
    ]
