# Generated by Django 5.2.17 on 2026-08-24 20:23

from django.db import migrations, models


def copy_language_fields(apps, schema_editor):
    Article = apps.get_model('website', 'Article')
    for article in Article.objects.all():
        lang = (article.language or 'sr')[:2]
        if lang == 'en':
            article.title_en = article.title_en or article.title
            article.excerpt_en = article.excerpt_en or article.excerpt
            article.body_en = article.body_en or article.body
            article.save(update_fields=['title_en', 'excerpt_en', 'body_en'])
        elif lang == 'ru':
            article.title_ru = article.title_ru or article.title
            article.excerpt_ru = article.excerpt_ru or article.excerpt
            article.body_ru = article.body_ru or article.body
            article.save(update_fields=['title_ru', 'excerpt_ru', 'body_ru'])


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_partner_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_en',
            field=models.TextField(blank=True, verbose_name='Tekst (English)'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_ru',
            field=models.TextField(blank=True, verbose_name='Tekst (русский)'),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt_en',
            field=models.TextField(blank=True, verbose_name='Kratak opis (English)'),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt_ru',
            field=models.TextField(blank=True, verbose_name='Kratak opis (русский)'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=220, verbose_name='Naslov (English)'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(blank=True, max_length=220, verbose_name='Naslov (русский)'),
        ),
        migrations.RunPython(copy_language_fields, migrations.RunPython.noop),
    ]
