# Generated by Django 5.2.17 on 2026-08-24 22:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def copy_amounts_to_payments(apps, schema_editor):
    Partner = apps.get_model('website', 'Partner')
    PartnerPayment = apps.get_model('website', 'PartnerPayment')
    for partner in Partner.objects.all():
        if PartnerPayment.objects.filter(partner=partner).exists():
            continue
        if partner.amount:
            PartnerPayment.objects.create(
                partner=partner,
                amount=partner.amount,
                paid_on=partner.recorded_on or django.utils.timezone.localdate(),
                note='',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_article_translations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-recorded_on', 'name'], 'verbose_name': 'Klijent', 'verbose_name_plural': 'Klijenti'},
        ),
        migrations.AddField(
            model_name='partner',
            name='due_on',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Naziv klijenta'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'Aktivan'),
                    ('pending', 'Na čekanju'),
                    ('completed', 'Završen'),
                    ('paused', 'Pauziran'),
                    ('late', 'Kasni sa plaćanjem'),
                ],
                db_index=True,
                default='active',
                max_length=20,
                verbose_name='Status',
            ),
        ),
        migrations.CreateModel(
            name='PartnerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Iznos')),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum rate')),
                ('note', models.CharField(blank=True, max_length=180, verbose_name='Napomena')),
                ('partner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='payments',
                    to='website.partner',
                    verbose_name='Klijent',
                )),
            ],
            options={
                'verbose_name': 'Rata',
                'verbose_name_plural': 'Rate',
                'ordering': ['paid_on', 'id'],
            },
        ),
        migrations.RunPython(copy_amounts_to_payments, migrations.RunPython.noop),
    ]
